# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("@rules_java//java:defs.bzl", "java_test")

package(default_visibility = ["//visibility:public"])

java_test(
	name = "CuckooFilterArrayTest",
	srcs = [
		"CuckooFilterArrayTest.java",
	],
	deps = [
		"//third_party/java/guava",
		"//third_party/java/junit",
		"//third_party/java/truth",
		"//third_party/java/mockito",
		"//java/com/google/setfilters/cuckoofilter",
	]
)

java_test(
	name = "CuckooFilterTest",
	srcs = [
		"CuckooFilterTest.java",
	],
	size = "medium",
	deps = [
		"//third_party/java/guava",
		"//third_party/java/junit",
		"//third_party/java/truth",
		"//third_party/java/mockito",
		"//java/com/google/setfilters/cuckoofilter",
	]
)

java_test(
	name = "CuckooFilterConfigTest",
	srcs = [
		"CuckooFilterConfigTest.java",
	],
	deps = [
		"//third_party/java/guava",
		"//third_party/java/junit",
		"//third_party/java/truth",
		"//third_party/java/mockito",
		"//java/com/google/setfilters/cuckoofilter",
	]
)

java_test(
	name = "CuckooFilterHashFunctionsTest",
	srcs = [
		"CuckooFilterHashFunctionsTest.java",
	],
	deps = [
		"//third_party/java/guava",
		"//third_party/java/junit",
		"//third_party/java/truth",
		"//third_party/java/mockito",
		"//java/com/google/setfilters/cuckoofilter",
	]
)

java_test(
	name = "CuckooFilterStrategiesTest",
	srcs = [
		"CuckooFilterStrategiesTest.java",
	],
	deps = [
		"//third_party/java/guava",
		"//third_party/java/junit",
		"//third_party/java/truth",
		"//third_party/java/mockito",
		"//java/com/google/setfilters/cuckoofilter",
	]
)

java_test(
	name = "CuckooFilterTableTest",
	srcs = [
		"CuckooFilterTableTest.java",
	],
	deps = [
		"//third_party/java/guava",
		"//third_party/java/junit",
		"//third_party/java/truth",
		"//third_party/java/mockito",
		"//java/com/google/setfilters/cuckoofilter",
	]
)

java_test(
	name = "SemiSortedCuckooFilterTableTest",
	srcs = [
		"SemiSortedCuckooFilterTableTest.java",
	],
	deps = [
		"//third_party/java/guava",
		"//third_party/java/junit",
		"//third_party/java/truth",
		"//third_party/java/mockito",
		"//java/com/google/setfilters/cuckoofilter",
	]
)

java_test(
	name = "SerializedCuckooFilterTableTest",
	srcs = [
		"SerializedCuckooFilterTableTest.java",
	],
	deps = [
		"//third_party/java/guava",
		"//third_party/java/junit",
		"//third_party/java/truth",
		"//third_party/java/mockito",
		"//java/com/google/setfilters/cuckoofilter",
	]
)
