name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  USE_JAVA_DISTRIBUTION: 'zulu'
  USE_JAVA_VERSION: '11'
  USE_BAZEL_VERSION: '4.2.1'

jobs:
  bazel-build:
    name: 'Bazel build'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/bazel-build
